version: '3'
services:
  corromics-streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: corromics-streamlit
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs:rw
    restart: unless-stopped
    command: /app/run_server.sh
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 8000M
    environment:
      VIRTUAL_HOST: corromics.gnps2.org
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: corromics.gnps2.org
      LETSENCRYPT_EMAIL: mwang87@gmail.com
      ENVIRONMENT_MODE: gnps
