name: gemelli-standalone
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - numpy<2
  - scikit-bio=0.5.9
  - iow<1.0.8
  - biom-format
  - pandas
  - scipy
  - scikit-learn
  - h5py
  - click
  - nose
  - pip
  - pip:
      - gemelli==0.0.12
