name: Build Corromics App for Windows and macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    env:
      APP_NAME: Corromics
      PYTHON_VERSION: 3.11.0

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Dependencies
      run: |
        python -m venv venv
        if [ "${{ runner.os }}" == "Windows" ]; then
          venv\Scripts\activate
        else
          source venv/bin/activate
        fi
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
      shell: bash
    
    # ✅ Debug Step: Verify Installed Packages
    - name: Debug Installed Packages
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          venv\Scripts\activate
        else
          source venv/bin/activate
        fi
        pip list
      shell: bash

    # ✅ WINDOWS MSI BUILD
    - name: Build Windows MSI Installer
      if: matrix.os == 'windows-latest'
      run: |
        curl -LO https://github.com/wixtoolset/wix3/releases/download/wix3111rtm/wix311-binaries.zip
        unzip wix311-binaries.zip -d wix
        rm wix311-binaries.zip

        venv\Scripts\activate
        pyinstaller --noconfirm Home.spec

        ./wix/heat.exe dir dist -gg -sfrag -sreg -srd -cg AppFiles -dr INSTALLDIR -out files.wxs
        ./wix/candle.exe files.wxs -o files.wixobj
        ./wix/light.exe -ext WixUIExtension -o ${{ env.APP_NAME }}.msi files.wixobj

    - name: Upload Windows Installer
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Corromics-Windows-Installer
        path: Corromics.msi

    # ✅ macOS .app BUILD
    - name: Build macOS App (.app)
      if: matrix.os == 'macos-latest'
      run: |
        source venv/bin/activate
        pyinstaller --noconfirm Home.spec
        mkdir dist_macos
        mv dist/*.app dist_macos/
      shell: bash

    - name: Upload macOS Build
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Corromics-macOS
        path: dist_macos/
