[global]
developmentMode = false

[server]
headless = true
port = 8501
enableCORS = false
maxUploadSize = 512

[theme]
base = "light"
primaryColor = "#0A74DA"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
